on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "build and push the image"
        run: |
          IMAGE_TAG="ghcr.io/luhring/example:git-$GITHUB_SHA"
          docker build -t "$IMAGE_TAG" .

          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u luhring --password-stdin
          docker push "$IMAGE_TAG"

  sign_image:
    needs: build_image
    runs-on: ubuntu-latest
    steps:
      - uses: sigstore/cosign-installer@main

      - name: "sign the image"
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u luhring --password-stdin
          echo "${{ secrets.COSIGN_KEY }}" > cosign.key
          cosign sign -key ./cosign.key "ghcr.io/luhring/example:git-$GITHUB_SHA"

  create_image_sbom:
    needs: build_image
    runs-on: ubuntu-latest
    steps:
      - name: "install Syft"
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: "create the SBOM"
        run: |
          IMAGE_TAG="ghcr.io/luhring/example:git-$GITHUB_SHA"
          syft "registry:$IMAGE_TAG" -o json | jq -c > ./sbom.syft.json

      - uses: actions/upload-artifact@v2
        with:
          name: sbom.syft.json
          path: ./sbom.syft.json

  scan_for_vulnerabilities:
    needs: create_image_sbom
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: sbom.syft.json

      - name: "install Grype"
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: "scan for vulnerabilities"
        # Normally, we'd fail the pipeline if we detected vulnerabilities above a threshold. For this example, we won't.
        run: |
          grype sbom:./sbom.syft.json -o json > ./vulnerability-scan.grype.json

      - uses: actions/upload-artifact@v2
        with:
          name: vulnerability-scan.grype.json
          path: ./vulnerability-scan.grype.json

  create_sbom_attestation:
    needs: create_image_sbom
    runs-on: ubuntu-latest
    container:
      image: golang:1.17-alpine
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: sbom.syft.json

      - run: |
          go install github.com/sigstore/cosign/cmd/cosign@main

      - name: "attest the sbom"
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          apk add docker
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u luhring --password-stdin
          echo "${{ secrets.COSIGN_KEY }}" > cosign.key

          SBOM_FILE="./sbom.syft.json"
          IMAGE_TAG="ghcr.io/luhring/example:git-$GITHUB_SHA"

          cosign attest -predicate "$SBOM_FILE" -key ./cosign.key "$IMAGE_TAG"
